export enum Role {

    ROLE_ADMIN = 'ROLE_ADMIN',
    ROLE_MANAGER = 'ROLE_MANAGER',
    ROLE_ACOUNTER = 'ROLE_ACOUNTER',
    ROLE_TECHNOLOGIST = 'ROLE_TECHNOLOGIST',
    ROLE_STOREKEEPER = 'ROLE_STOREKEEPER',
    ROLE_CMO = 'ROLE_CMO',
    ROLE_CTO = 'ROLE_CTO',
    ROLE_ECONOMIST = 'ROLE_ECONOMIST',
    ROLE_CEO = 'ROLE_CEO'
    
}
