export enum Role {

    ADMIN = 'ROLE_ADMIN',
    MANAGER = 'ROLE_MANAGER',
    ACOUNTER = 'ROLE_ACOUNTER',
    TECHNOLOGIST = 'ROLE_TECHNOLOGIST',
    STOREKEEPER = 'ROLE_STOREKEEPER',
    CMO = 'ROLE_CMO',
    CTO = 'ROLE_CTO',
    ROLE_ECONOMIST = 'ROLE_ECONOMIST',
    ROLE_CEO = 'ROLE_CEO'
    
}
